#!/usr/bin/env python

import RPi.GPIO as GPIO
import os
import time
import sys

power_off_detect_pin = 13

def usage():
	print "Usage: power_switch [cmd] "
	print "    help         display the help and exit"
	print "    enable       enable power switch "
	print "    disable      disable power switch\n\n"

def setup():
	GPIO.setmode(GPIO.BCM)
	GPIO.setup(power_off_detect_pin, GPIO.IN, pull_up_down=GPIO.PUD_UP)
	if len(sys.argv)<2:
			print "Too few argument\n"
			usage()
			quit()
	elif len(sys.argv)>2:
			print "Too many arguments\n"
			usage()
			quit()
	else:
		if sys.argv[1] == "enable":
			print "power_switch enabled"
			GPIO.add_event_detect(power_off_detect_pin, GPIO.FALLING, power_off_detect)
		elif sys.argv[1] == "disable":
			print "power_switch disabled"
			GPIO.remove_event_detect(power_off_detect_pin)
		elif sys.argv[1] == "help":
			usage()
			quit()
		else:
			print "Wrong argument\n"
			usage()
			quit()

def power_off_detect(channel):
	os.system("sudo poweroff")

def main():
	while True:

		time.sleep(1)

if __name__ == '__main__':
	setup()
	main()
